name: Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Boost
        run: |
          choco install boost-msvc-14.3 -y
      - name: cmake
        run: |
          cmake -S . -B build `
            -DBOOST_ROOT="C:/local/boost_1_87_0" `
            -DBoost_INCLUDE_DIR="C:/local/boost_1_87_0" `
            -DBoost_LIBRARY_DIR="C:/local/boost_1_87_0/lib64-msvc-14.3" `
            -DBoost_USE_STATIC_LIBS=ON `
            -DBoost_NO_BOOST_CMAKE=ON `
            -DCMAKE_CXX_STANDARD=11 `
            -DCMAKE_CXX_STANDARD_REQUIRED=ON
      - name: Compile
        working-directory: build
        run: cmake --build . -j2
      - name: Test
        working-directory: build
        run: ctest -j2
