name: Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Boost
        run: |
          choco install boost-msvc-14.3 -y
      - name: cmake
        run: |
          cmake -E make_directory build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="${env:VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_STANDARD_REQUIRED=ON ..
      - name: Compile
        working-directory: build
        run: cmake --build . -j2
      - name: Test
        working-directory: build
        run: ctest -j2
