name: Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache vcpkg
        uses: actions/cache@v3
        id: vcpkg-cache
        with:
          path: |
            vcpkg
            !vcpkg/.git
            !vcpkg/downloads
            !vcpkg/buildtrees
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}-v2
      - name: Setup vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg integrate install
          ./vcpkg install `
            boost-program-options:x64-windows `
            boost-system:x64-windows `
            boost-thread:x64-windows `
            boost-test:x64-windows `
            boost-interprocess:x64-windows `
            boost-iostreams:x64-windows `
            boost-ptr-container:x64-windows
          echo "VCPKG_ROOT=$PWD" >> $env:GITHUB_ENV
      - name: cmake
        run: |
          cmake -S . -B build `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_CXX_STANDARD=11 `
            -DCMAKE_CXX_STANDARD_REQUIRED=ON `
            -DCMAKE_CXX_FLAGS="/EHsc /DWIN32" `
            -DCMAKE_VERBOSE_MAKEFILE=ON
      - name: Build with diagnostics
        run: |
          cmake --build build --config Release --parallel 2 --verbose
      - name: Test
        working-directory: build
        run: ctest -j2
