name: Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg integrate install
          ./vcpkg install boost-program-options:x64-windows-static boost-system:x64-windows-static boost-thread:x64-windows-static boost-test:x64-windows-static
          echo "VCPKG_ROOT=$PWD" >> $env:GITHUB_ENV
      - name: cmake
        run: |
          cmake -S . -B build `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows-static `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_CXX_STANDARD=11 `
            -DCMAKE_CXX_STANDARD_REQUIRED=ON
      - name: Compile
        working-directory: build
        run: cmake --build . -j2
      - name: Test
        working-directory: build
        run: ctest -j2
